// @generated by Cratis. Source: Arc.React.Ideas.Board.CaptureIdea. Time: 2026-08-22T23:19:49.8284800Z. Hash: 156E2ECC7FA563E054A6FD024D6DDC4F143886560BE76A37C36B74F5058FF49A
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

/**
 * Captures a new idea in the current-state board.
 */
export interface ICaptureIdea {
    
    /**
     * The identifier assigned by the client.
     */
    id?: Guid;
    
    /**
     * The detail that makes the idea useful.
     */
    summary?: string;
    
    /**
     * The concise idea title.
     */
    title?: string;
}

export class CaptureIdeaValidator extends CommandValidator<ICaptureIdea> {
    constructor() {
        super();
        this.ruleFor(c => c.summary).notEmpty();
        this.ruleFor(c => c.summary).maxLength(240);
        this.ruleFor(c => c.title).notEmpty();
        this.ruleFor(c => c.title).maxLength(72);
    }
}

/**
 * Captures a new idea in the current-state board.
 */
export class CaptureIdea extends Command<ICaptureIdea> implements ICaptureIdea {
    readonly route: string = '/api/ideas/board';
    readonly validation: CommandValidator = new CaptureIdeaValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Guid, false),
        new PropertyDescriptor('summary', String, false),
        new PropertyDescriptor('title', String, false),
    ];

    private _id!: Guid;
    private _summary!: string;
    private _title!: string;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The identifier assigned by the client.
     */
    get id(): Guid {
        return this._id;
    }

    set id(value: Guid) {
        this._id = value;
        this.propertyChanged('id');
    }
    /**
     * The detail that makes the idea useful.
     */
    get summary(): string {
        return this._summary;
    }

    set summary(value: string) {
        this._summary = value;
        this.propertyChanged('summary');
    }
    /**
     * The concise idea title.
     */
    get title(): string {
        return this._title;
    }

    set title(value: string) {
        this._title = value;
        this.propertyChanged('title');
    }

    static use(initialValues?: ICaptureIdea): [CaptureIdea, SetCommandValues<ICaptureIdea>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<CaptureIdea, ICaptureIdea>(CaptureIdea, initialValues);
    }
}
