// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Arc.React.Ideas.Board.Idea. Time: 2026-10-05T15:54:07.3805211Z. Hash: 880CB40093293EA69C0FD66BFC8EE99830217D643829C4BE000E2D71B826A0DA
// **DO NOT EDIT** - This file is an automatically generated file.
import { field } from '@cratis/fundamentals';
import { Guid } from '@cratis/fundamentals';

/**
 * Represents an idea shown on the board.
 */
export class Idea {

    /**
     * The idea identifier.
     */
    @field(Guid)
    id!: Guid;

    /**
     * The concise idea title.
     */
    @field(String)
    title!: string;

    /**
     * The useful idea detail.
     */
    @field(String)
    summary!: string;
}
