// @generated by Cratis. Source: Arc.React.Ideas.Board.Idea. Time: 2026-08-22T23:19:49.8499690Z. Hash: 6743C6D2B074DAA3A766C72BCE5AAD763719C1C339375148ACCB982DC62E8159
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { Guid } from '@cratis/fundamentals';

/**
 * Represents an idea shown on the board.
 */
export class Idea {

    /**
     * The idea identifier.
     */
    @field(Guid)
    id!: Guid;

    /**
     * The concise idea title.
     */
    @field(String)
    title!: string;

    /**
     * The useful idea detail.
     */
    @field(String)
    summary!: string;
}
