// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

// @generated by Cratis. Source: Arc.React.Ideas.Board.Idea. Time: 2026-10-05T15:54:07.3430780Z. Hash: 0A2CDCA3D3FADAD6FB1DBB0B55977CBFB199E175986445BF20BF55B29036F298
// **DO NOT EDIT** - This file is an automatically generated file.
import { ChangeSet, ObservableQueryFor, Paging, QueryResultWithState, Sorting } from '@cratis/arc/queries';
import { ObservableQueryWhen, SetPage, SetPageSize, SetSorting, useChangeStream, useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Idea } from './Idea';

class ObserveIdeasSortBy {

    constructor(readonly query: ObserveIdeas) {
    }

}

class ObserveIdeasSortByWithoutQuery {

}


/**
 * Observes all captured ideas and pushes the current board on each change.
 */
export class ObserveIdeas extends ObservableQueryFor<Idea[]> {
    readonly route: string = '/api/ideas/board/observe-ideas';
    readonly queryName: string = 'Arc.React.Ideas.Board.Idea.ObserveIdeas';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Idea[] = [];
    private readonly _sortBy: ObserveIdeasSortBy;
    private static readonly _sortBy: ObserveIdeasSortByWithoutQuery = new ObserveIdeasSortByWithoutQuery();

    constructor() {
        super(Idea, true);
        this._sortBy = new ObserveIdeasSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): ObserveIdeasSortBy {
        return this._sortBy;
    }

    static get sortBy(): ObserveIdeasSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<Idea[]>, SetSorting] {
        return useObservableQuery<Idea[], ObserveIdeas>(ObserveIdeas, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Idea[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Idea[], ObserveIdeas>(ObserveIdeas, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<Idea[]>, SetSorting] {
        return useSuspenseObservableQuery<Idea[], ObserveIdeas>(ObserveIdeas, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<Idea[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<Idea[], ObserveIdeas>(ObserveIdeas, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: Idea) => unknown, sorting?: Sorting): ChangeSet<Idea> {
        return useChangeStream<Idea, ObserveIdeas>(ObserveIdeas, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<ObserveIdeas, Idea[]> {
        return new ObservableQueryWhen<ObserveIdeas, Idea[]>(ObserveIdeas, condition);
    }
}
