checksumBehavior: update

nodeLinker: node-modules

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"

plugins:
  - path: .yarn/plugins/plugin-disable-typescript-compat.cjs
    spec: "plugin-disable-typescript-compat"

pnpMode: loose

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

yarnPath: .yarn/releases/yarn-4.5.3.cjs
