
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Quickstart.Dialogs {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class AddBook : Terminal.Gui.Views.Dialog {
        
        private Terminal.Gui.Views.Label label;
        
        private Terminal.Gui.Views.TextField _title;
        
        private Terminal.Gui.Views.Label label2;
        
        private Terminal.Gui.Views.TextField _author;
        
        private Terminal.Gui.Views.Label label3;
        
        private Terminal.Gui.Views.TextField _isbn;
        
        private void InitializeComponent() {
            this._isbn = new Terminal.Gui.Views.TextField();
            this.label3 = new Terminal.Gui.Views.Label();
            this._author = new Terminal.Gui.Views.TextField();
            this.label2 = new Terminal.Gui.Views.Label();
            this._title = new Terminal.Gui.Views.TextField();
            this.label = new Terminal.Gui.Views.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Auto();
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Movable;
            this.Modal = true;
            this.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Title = "";
            this.label.Width = Dim.Auto();
            this.label.Height = 1;
            this.label.X = 1;
            this.label.Y = 1;
            this.label.Visible = true;
            this.label.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.label.Data = "label";
            this.label.Text = "Title";
            this.label.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label);
            this._title.Width = Dim.Fill(1);
            this._title.Height = 1;
            this._title.X = 1;
            this._title.Y = 2;
            this._title.Visible = true;
            this._title.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this._title.Secret = false;
            this._title.Data = "_title";
            this._title.Text = "";
            this._title.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this._title);
            this.label2.Width = Dim.Auto();
            this.label2.Height = 1;
            this.label2.X = 1;
            this.label2.Y = 4;
            this.label2.Visible = true;
            this.label2.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.label2.Data = "label2";
            this.label2.Text = "Author";
            this.label2.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label2);
            this._author.Width = Dim.Fill(1);
            this._author.Height = 1;
            this._author.X = 1;
            this._author.Y = 5;
            this._author.Visible = true;
            this._author.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this._author.Secret = false;
            this._author.Data = "_author";
            this._author.Text = "";
            this._author.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this._author);
            this.label3.Width = Dim.Auto();
            this.label3.Height = 1;
            this.label3.X = 1;
            this.label3.Y = 7;
            this.label3.Visible = true;
            this.label3.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this.label3.Data = "label3";
            this.label3.Text = "ISBN";
            this.label3.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this.label3);
            this._isbn.Width = Dim.Fill(1);
            this._isbn.Height = 1;
            this._isbn.X = 1;
            this._isbn.Y = 8;
            this._isbn.Visible = true;
            this._isbn.Arrangement = Terminal.Gui.ViewBase.ViewArrangement.Fixed;
            this._isbn.Secret = false;
            this._isbn.Data = "_isbn";
            this._isbn.Text = "";
            this._isbn.TextAlignment = Terminal.Gui.ViewBase.Alignment.Start;
            this.Add(this._isbn);
        }
    }
}
