
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Quickstart.Dialogs {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;


    public partial class Books : Terminal.Gui.Dialog {

        private Terminal.Gui.ListView _books;

        private void InitializeComponent() {
            this._books = new Terminal.Gui.ListView();
            this.Width = Dim.Percent(90);
            this.Height = Dim.Percent(80);
            this.X = Pos.Center();
            this.Y = Pos.Center();
            this.Visible = true;
            this.Arrangement = Terminal.Gui.ViewArrangement.Movable;
            this.Modal = true;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "";
            this._books.Width = Dim.Fill(20);
            this._books.Height = Dim.Fill(3);
            this._books.X = 0;
            this._books.Y = 0;
            this._books.Visible = true;
            this._books.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this._books.Data = "_books";
            this._books.TextAlignment = Terminal.Gui.Alignment.Start;
            this._books.Source = new Terminal.Gui.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] {
                            "Item1",
                            "Item2",
                            "Item3"}));
            this._books.AllowsMarking = false;
            this._books.AllowsMultipleSelection = true;
            this.Add(this._books);
        }
    }
}
