
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v2.0.0.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Quickstart {
    using System;
    using Terminal.Gui;
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Drawing;
    
    
    public partial class Library : Terminal.Gui.Window {
        
        private Terminal.Gui.ListView _mainMenu;
        
        private void InitializeComponent() {
            this._mainMenu = new Terminal.Gui.ListView();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Arrangement = (Terminal.Gui.ViewArrangement.Movable | Terminal.Gui.ViewArrangement.Overlapped);
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.Alignment.Start;
            this.Title = "Library (ESC to quit)";
            this._mainMenu.Width = Dim.Fill(20);
            this._mainMenu.Height = Dim.Fill(20);
            this._mainMenu.X = 0;
            this._mainMenu.Y = 0;
            this._mainMenu.Visible = true;
            this._mainMenu.Arrangement = Terminal.Gui.ViewArrangement.Fixed;
            this._mainMenu.Data = "_mainMenu";
            this._mainMenu.TextAlignment = Terminal.Gui.Alignment.Start;
            this._mainMenu.Source = new Terminal.Gui.ListWrapper<string>(new System.Collections.ObjectModel.ObservableCollection<string>(new string[] {
                            "Initialize with books",
                            "Add book to inventory",
                            "Borrow book",
                            "Return book",
                            "Set book as overdue",
                            "Reserve book",
                            "Cancel reservation"}));
            this._mainMenu.AllowsMarking = false;
            this._mainMenu.AllowsMultipleSelection = true;
            this.Add(this._mainMenu);
        }
    }
}
